name: darell_trading_plan
description: DARELL V10 Trading Plan - Scalping Swing Hammer Doji Engulfing
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
